### 7.1 PEP 8
Nie każdy kod, który się wykonuje jest poprawnie napisany. Istnieje szereg zaleceń dotyczących właściwego formatowania kodu. Są one opisane w dokumencie o nazwie [PEP 8](https://peps.python.org/pep-0008/). Poniżej znajduje się kilka przykładów:

1. Używamy snake case'a
```python
# Dobrze
variable_name = "abc"


# Źle
variableName = "abc"
```

---
2. Zalecana maksymalna długość linii to 79 znaków
Ta reguła często jest świadomie ignorowana. Jeśli posiadanie w kodzie dłuższych linii nam nie przeszkadza, możemy zwiększyć długość np. do 100 znaków. Dobrze jednak jest mieć z góry określone maksimum i nie przekraczać go.

---
3. Maksymalnie dwie linie przerwy w kodzie. Kiedy jesteśmy wewnątrz funkcji - maksymalnie jedna

```python
print(2+2)

print(2+2)  # jedna linia przerwy


print(2+2)  # dwie linie przerwy



print(2+2)  # trzy linie przerwy - za dużo
```

---
4. Spacje wokół operatora przypisania podczas tworzenia zmiennych
```python
# Dobrze
x = 1


# Źle
x=1
```

---
5. Brak spacji wokół operatora przypisania podczas przekazywania argumentów do funkcji
```python
# Dobrze
def func(a=1, b=2):
    return a + b


# Źle
def func(a = 1, b = 2):
    return a + b
```

**PEP 8 - podsumowanie:**
- Istnieje szereg zaleceń dotyczących pisania poprawnego stylistycznie kodu - można znaleźć jej w PEP 8
- Trzymanie się tych zasad sprawi że kod będzie bardziej czytelny a także zachowa spójność kiedy pracuje nad nim więcej osób
---
---
---
&nbsp;
### 7.2 Type annotations
Python jest językiem typowanym dynamicznie, w związku z czym deklarowanie typów zmiennych czy argumentów funkcji nie jest konieczne. Istnieje jednak taka możliwość i korzystanie z niej sprawia, że kod jest bardziej czytelny. Dzięki temu kiedy widzimy po raz pierwszy definicję funkcji czy zmiennej od razu wiemy jakich typów danych możemy się tam spodziewać.

Typy danych dla argumentów funkcji czy zmiennych anotujemy w następujący sposób:
```python
def determine_winner(human_power: float, zombie_power: float) -> int:
    """
    This function takes human power and zombie power as inputs,
    compares them and returns information about the battle result
    
    Args:
        human_power (float): power of a human
        zombie_power (float): power of a zombie
    
    Returns:
        (int): result of the battle where 1 is human's victory,
               -1 is zombie's victory and 0 is a draw
    """
    
    if human_power > zombie_power:
        return 1
    elif human_power < zombie_power:
        return -1
    else:
        return 0


winner: int = determine_winner(4.23, 5.24)
```

Jeśli chcemy aby jakaś zmienna / argument mogły przyjmować więcej niż jeden typ, należy użyć `Union` z biblioteki `typing`:

```python
from typing import Union


def determine_winner(human_power: Union[int, float], zombie_power: Union[int, float]) -> int:
    """
    This function takes human power and zombie power as inputs,
    compares them and returns information about the battle result
    
    Args:
        human_power (float): power of a human
        zombie_power (float): power of a zombie
    
    Returns:
        (int): result of the battle where 1 is human's victory,
               -1 is zombie's victory and 0 is a draw
    """
    
    if human_power > zombie_power:
        return 1
    elif human_power < zombie_power:
        return -1
    else:
        return 0
```

***Type annotations* - podsumowanie:**
- Deklarowanie typów dla zmiennych oraz argumentów funkcji jest w Pythonie opcjonalne
- Deklarowanie ich (poprzez *type annotations*) zwiększa czytelność kodu i pozwala się w nim lepiej orientować
- Jeśli nie będziemy przestrzegać deklaracji dotyczących typów danych program będzie działał poprawnie, chociaż niektóre IDE mogą podkreślać taki kod
---
---
---
&nbsp;
### 7.3 Stack Overflow
Jednym z nieodłącznych elementów programowania jest szukanie rozwiązań pojawiających się problemów w internecie. Często odpowiedzi na nasze pytania są już przygotowane i znajdują się na [Stack Overflow](https://stackoverflow.com/). Jest to serwis, na którym programiści mogą zapytać o to jak rozwiązać pewien problem albo co oznacza błąd, którego nie rozumieją. 

Linki do Stacka często pojawiają się wysoko w wynikach wyszukiwania:
![[stack1.png]]

![[stack2.png]]

Jedną z zalet Stack Overflow jest system punktacji zarówno pytań jak i odpowiedzi, który zwiększa widoczność najbardziej wartościowych treści.

**Stack Overflow - podsumowanie:**
- Podczas programowania często napotykamy problemy, które zostały już rozwiązane przez kogoś innego
- Wiele z nich zostało opisanych na Stack Overflow - serwisie dla programistów, którego celem jest opisywanie i rozwiązywanie tego typu problemów 
---
---
---
&nbsp;
### 7.4 Debugowanie
Debugowanie (ang. *debugging*) to proces szukania i naprawiania błędów w programie. Istnieją różne sposoby na to żeby zlokalizować błędny zapis w kodzie. Przykładowe dwa to:

#### 7.4.1 Analiza *tracebacku*
*Traceback* to komunikat, który zostaje wyświetlony w terminalu w momencie kiedy w trakcie wykonywania programu pojawi się błąd. Zawiera on informację o tym, w której linijce znajduje się problem a także - jeśli wywołujemy tam jakąś funkcję - gdzie błąd zlokalizowany jest w tej funkcji. W ten sposób możemy dokładnie prześledzić łańcuch wywołań kolejnych funkcji i zlokalizować buga.

W poniższym kodzie w funkcji `decide_where_to_move` znajduje się błąd:

```python
def decide_where_to_move(human, zombies_list):
    # Okodowanie procesu decyzyjnego
    new_x = human["x"] + "1"   # !!! w tej linijce jest błąd
    new_y = human["y"] + "1"
    return new_x, new_y


def move_all_humans(humans_list, zombies_list):
    for h in humans_list:
        new_x, new_y = decide_where_to_move(h, zombies_list)
        h["x"] = new_x
        h["y"] = new_y
    return humans_list


humans_list = [{"x": 1, "y": 2, "velocity": 5, "power": 3}]
zombies_list = [{"x": 4, "y": -3, "power": 5}, {"x": 8, "y": 0, "power": 6}]

humans_list = move_all_humans(humans_list, zombies_list)
```

Po próbie uruchomienia skryptu pojawi się następujący komunikat:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 4>()
      1 humans_list = [{"x": 1, "y": 2, "velocity": 5, "power": 3}]
      2 zombies_list = [{"x": 4, "y": -3, "power": 5}, {"x": 8, "y": 0, "power": 6}]
----> 4 humans_list = move_all_humans(humans_list, zombies_list)

Input In [2], in move_all_humans(humans_list, zombies_list)
      1 def move_all_humans(humans_list, zombies_list):
      2     for h in humans_list:
----> 3         new_x, new_y = decide_where_to_move(h, zombies_list)
      4         h["x"] = new_x
      5         h["y"] = new_y

Input In [1], in decide_where_to_move(human, zombies_list)
      1 def decide_where_to_move(human, zombies_list):
      2     # Okodowanie procesu decyzyjnego
----> 3     new_x = human["x"] + "1" 
      4     new_y = human["y"] + "1"
      5     return new_x, new_y

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

#### 7.4.2 Debuger w IDE
Debuger jest narzędziem, które pozwala zatrzymać wykonywanie programu w zadanym miejscu i podejrzeć wartości poszczególnych zmiennych czy wyrażeń wpisywanych do terminala. Aby podczas debugowania zatrzymać kod na określonej linijce należy postawić przy niej *breakpoint* klikając w odpowiednim miejscu między numerem linii a samym kodem:

![[debuger1.png]]

Wykonując skrypt należy wybrać opcję *Debug* zamiast *Run*. Kiedy program dotrze do *breakpointa* - zatrzyma się. Możemy wówczas między innymi:
- wpisywać do terminala wyrażenia, których wartość chcemy wyznaczyć (np. `humans_list[0]["x"]`)
- przejść do kolejnej linijki w ramach scope'u, w którym się znajdujemy (w PyCharmie nazywa się to `Step Over`)
- wejść do środka funkcji, której wywołanie znajduje się w aktualnej linii (w PyCharmie nazywa się to `Step Into`)

**Debugowanie - podsumowanie:**
- Proces lokalizacji oraz eliminacji błędów w kodzie nazywa się *debugowaniem*
- Jednym ze sposób debugowania jest analiza *tracebacku* czyli komunikatu, który pojawia się w terminalu po wystąpieniu błędu
- Przydatnym narzędziem podczas szukania błędów jest debuger, który pozwala zatrzymać wykonywanie programu w dowolnym miejscu
---
---
---
&nbsp;
### 7.5 Linebreak
Jeśli linijka kodu jest zbyt długa możemy na różne sposoby ją złamać, czyli przenieść jej część do kolejnej linii. Takie przeniesienie nazywane jest *linebreak*. 

Jeśli definiujemy strukturę danych możemy wstawić nową linię po dowolnym jej elemencie:

```python
list_of_zombies = [
    {"class": "Zombie",
     "x": 1,
     "y": 2
    },
    {
        "class": "Zombie",
        "x": -1.1,
        "y": 13.2
    },
    
    {
        "class": "Zombie",
        "x": -4,
        "y": 12
    }
]
```

Podobnie ma to miejsce w przypadku definicji czy wywołania funkcji z wieloma parametrami:

```python
def multi_parameter_function(a, b,
							 c, d):
	return a * b * c * d


multi_parameter_function(a=1, b=2,
						 c=3, d=4)
```

W pozostałych wypadkach możemy użyć znaku `\` np. przed operatorem takim jak `+` czy `-`:

```python
1 + 1 + 1 + 1 + 1 + 1 + 1 \
    + 1 + 1 + 1 + 1
```

Wówczas kolejna linia powinna być wcięta. Możemy również w ten sposób podzielić długiego stringa:

```python
lorem_ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit," \
              "sed do eiusmod tempor incididunt ut labore et dolore" \
              "magna aliqua. Ut enim ad minim veniam, quis nostrud " \
              "exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

```

Inną metodą podziału linii jest zapis całości w nawiasach okrągłych:

```python
lorem_ipsum = ("Lorem ipsum dolor sit amet, consectetur adipiscing elit,"
              "sed do eiusmod tempor incididunt ut labore et dolore"
              "magna aliqua. Ut enim ad minim veniam, quis nostrud "
              "exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
```

```python
x = (1 + 2 + 3 + 4
     + 5 + 6 + 7)
```

**Linebreak - podsumowanie:**
- Jeżeli linia kodu jest zbyt długa należy ją złamać, czyli zastosować *linebreak*
- W strukturach danych przejście do nowej linii może nastąpić po dowolnym elemencie kolekcji. Podobnie podczas definicji czy wywołania funkcji z wieloma parametrami
- W pozostałych przypadkach *linebreak* może być oznaczony również poprzez znak `\`
- Jeśli kod znajdzie się w nawiasach okrągłych możemy zapisać go w kilku linijkach
---
---
---
&nbsp;
### 7.6 Wyjątki
Jeżeli z jakiegoś powodu napisany przez nas kod nie będzie mógł zostać wykonany, interpreter zwróci błąd, nazywany również wyjątkiem (ang. *exception*).

#### 7.6.1 Rodzaje błędów / wyjątków
Poniżej znajdują się przykłady najczęściej spotykanych błędów.

**SyntaxError**
```python
>>> 2 + '

# ---
Input In [1]
    2 + '
         ^
SyntaxError: EOL while scanning string literal
```

**TypeError**
```python
>>> "a" * "b"

# ---
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 "a" * "b"

TypeError: can't multiply sequence by non-int of type 'str'
```

**AttributeError**
```python
>>> [1, 2, 3].add([3, 4])

# ---
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 [1, 2, 3].add([3, 4])

AttributeError: 'list' object has no attribute 'add'
```

**ZeroDivisionError**
```python
>>> 2 / 0

# ---
ZeroDivisionError                         Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 2 / 0

ZeroDivisionError: division by zero
```

**NameError**
```python
>>> xyz

# ---
NameError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 xyz

NameError: name 'xyz' is not defined
```

**ValueError**
```python
>>> int("a")

# ---
ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 int("a")

ValueError: invalid literal for int() with base 10: 'a'
```

#### 7.6.2 `try-except`
Czasami chcemy wykonać jakiś kawałek kodu, ale spodziewamy się że może pojawić się w nim określony błąd. Możemy zapisać taki kod w bloku `try` i "przechwycić" wyjątek za pomocą `except`. Następnie znajduje się blok kodu, który zostanie wykonany jeśli wystąpi dany błąd.

W poniższym przykładzie dzielimy przez siebie liczby `a` i `b`, ale jeśli okaże się że `b` jest równe 0 zwracamy `None`:

```python
def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None
```

Możemy również przygotować blok `except` na dowolny błąd przechwytując każdy wyjątek (`Exception`) - zwykle aliasowany jako `e`:

```python
def divide(a, b):
    try:
        return a / b
    except Exception as e:
        print(e)
        return None
```

#### 7.6.3 Generowanie wyjątków
Może się zdarzyć, że chcemy jakiś wyjątek wygenerować samodzielnie. Używamy do tego słowa kluczowego `raise`, nazwy błędu oraz komunikatu jaki ma zostać wyświetlony:

```python
raise TypeError("Błędny typ")

# ---
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 raise TypeError("Błędny typ")

TypeError: Błędny typ
```

```python
numbers = [1, 2, 0, 3]
for number in numbers:
    if number == 0:
        raise Exception("Wartość jest równa 0!")
    
    print(1 / number)
```

#### 7.6.4 `assert`
Jeżeli w dowolnym miejscu kodu chcemy upewnić się że pewien warunek logiczny jest spełniony - a jeśli nie jest wyrzucić błąd - możemy użyć słowa kluczowego `assert`.

```python
x = 2

assert x == 1

print("x jest równe 1")
```

Ze względu na niespełnienie warunku logicznego za `assert` powyższy kod zwróci następujący błąd:

```python
AssertionError                            Traceback (most recent call last)
Input In [2], in <cell line: 3>()
      1 x = 2
----> 3 assert x == 1
      5 print("x jest równe 1")

AssertionError:
```

Inny przykład użycia `assert`:

```python
even_numbers = [0, 2, 4, 6, 8]

def check_if_even(list_):
    for item in list_:
        assert item % 2 == 0
    
    print("All numbers are even")

check_if_even(even_numbers)
```

**Wyjątki - podsumowanie:**
- Różne rodzaje błędów wykonywania programu zwracają różne wyjątki. Zwrócenie wyjątku przerywa działanie programu
- Aby pojawienie się błędu nie przerwało pracy programu używamy konstrukcji `try-except`, która pozwala przechwycić dowolny wyjątek
- Możemy podnieść wyjątek za pomocą słowa kluczowego `raise`
- Aby upewnić się, że pewien warunek jest spełniony używamy słowa kluczowego `assert`. Niespełnienie warunku spowoduje wyrzucenie błędu
---
---
---
&nbsp;
